version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-node"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-tdn9l18u0cy8"
s3_prefix = "sam-app-node"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
